name: Dependabot Automerge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Collect Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.3.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          compat-lookup: true
      - name: Enable auto-merge for pull request
        if: ${{ fromJSON(steps.metadata.outputs.compatibility-score) >= 80 }}
        run: gh pr merge --auto -s "$URL"
        env:
          URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
