name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove existing containers
        run: if [[ $(docker ps -qa --filter ancestor=nas) ]]; then docker stop $(docker ps -qa --filter ancestor=nas); docker rm $(docker ps -qa --filter ancestor=nas); fi
      - name: Remove outdated images
        run: if [[ $(docker images nas -qa) ]]; then docker rmi $(docker images nas -qa); fi
      - name: Build Docker image
        run: docker build -t nas .
      - name: Run Docker container
        run: docker run -v store:/store -p 80:8192 --name nas -d nas
